Repository research-software-directory/RSD-as-a-service, pull requests merged in 2022-06, with the labels that each got.

#311 add makefile to ease the install, build process and run services in development mode
  Makefile
  README.md
  documentation/docs/.vuepress/config.js
  frontend/components/layout/AppFooter.tsx
Labels: UX fix

#312 305: Organisation maintainers management
  database/015-create-maintainer-tables.sql
  database/100-create-api-views.sql
  frontend/auth/api/authHelpers.ts
  frontend/components/organisation/maintainers/OrganisationMaintainerLink.tsx
  frontend/components/organisation/maintainers/OrganisationMaintainersList.tsx
  frontend/components/organisation/maintainers/index.tsx
  frontend/components/organisation/maintainers/useOrganisationMaintainer.tsx
  frontend/pages/invite/organisation/[id].tsx
Labels: feature

#315 Save button listening to Ctrl + Enter
  frontend/README.md
  frontend/components/form/SubmitButtonWithListener.tsx
  frontend/components/mention/EditMentionModal.tsx
  frontend/components/organisation/settings/index.tsx
  frontend/components/organisation/units/ResearchUnitModal.tsx
  frontend/components/projects/add/AddProjectCard.tsx
  frontend/components/projects/edit/EditProjectStickyHeader.tsx
  frontend/components/projects/edit/team/TeamMemberModal.tsx
  frontend/components/software/add/AddSoftwareCard.tsx
  frontend/components/software/edit/EditSoftwareStickyHeader.tsx
  frontend/components/software/edit/contributors/EditContributorModal.tsx
  frontend/components/software/edit/organisations/EditOrganisationModal.tsx
  frontend/components/software/edit/testimonials/EditTestimonialModal.tsx
Labels: feature

#339 288 & 337: Nothing to show/no content (animated) message and warning on large file upload
  docker-compose.yml
  frontend/components/form/ControlledTextField.tsx
  frontend/components/layout/FlexibleGridSection.tsx
  frontend/components/layout/NoContent.tsx
  frontend/components/organisation/OrganisationGrid.tsx
  frontend/components/organisation/project/index.tsx
  frontend/components/organisation/settings/OrganisationLogo.tsx
  frontend/components/organisation/software/index.tsx
  frontend/components/organisation/units/ResearchUnitModal.tsx
  frontend/components/projects/ProjectsGrid.tsx
  frontend/components/projects/edit/information/ProjectImage.tsx
  frontend/components/projects/edit/team/TeamMemberModal.tsx
  frontend/components/software/ContributorsList.tsx
  frontend/components/software/PersonalInfo.tsx
  frontend/components/software/SoftwareGrid.tsx
  frontend/components/software/edit/contributors/EditContributorModal.tsx
  frontend/components/software/edit/information/ValidateConceptDoi.tsx
  frontend/components/software/edit/organisations/EditOrganisationModal.tsx
  frontend/package.json
  frontend/pages/projects/[slug]/index.tsx
  frontend/pages/software/[slug]/index.tsx
  frontend/utils/fetchHelpers.ts
  frontend/utils/getDataCite.ts
Labels: feature

#336 Add call to action to Landing page
  frontend/pages/index.tsx
Labels: UX fix

#309 Styled AppHeader
  docker-compose.yml
  documentation/README.md
  documentation/docs/navigation.md
  frontend/assets/LogoApp.svg
  frontend/components/AppHeader/AddMenu.test.tsx
  frontend/components/AppHeader/AddMenu.tsx
  frontend/components/AppHeader/JavascriptSupportWarning.tsx
  frontend/components/AppHeader/index.tsx
  frontend/components/layout/AppHeader.tsx
  frontend/components/layout/AppMenuItem.tsx
  frontend/components/layout/DefaultLayout.tsx
  frontend/components/layout/EditButton.tsx
  frontend/components/svg/LogoRSD.tsx
  frontend/config/menuItems.ts
  frontend/pages/index.tsx
  frontend/pages/projects/[slug]/index.tsx
  frontend/pages/projects/add.tsx
  frontend/pages/software/[slug]/index.tsx
  frontend/pages/software/add.tsx
  frontend/styles/global.css
Labels: UX fix, technical-debt
