Repository research-software-directory/RSD-as-a-service, pull requests merged in 2022-09, with the labels that each got.

#490 Add new favicon and icons for multiple platforms
  frontend/public/android-chrome-192x192.png
  frontend/public/android-chrome-512x512.png
  frontend/public/apple-touch-icon.png
  frontend/public/favicon-16x16.png
  frontend/public/favicon-32x32.png
  frontend/public/favicon.ico
  frontend/public/site.webmanifest
Labels: Design

#489 Fix responsive menu on narrow devices
  frontend/components/AppHeader/index.tsx
  frontend/components/GlobalSearchAutocomplete/index.tsx
  frontend/components/icons/enterkey.svg
Labels: UX fix

#535 fix: show homepage counts, align count props with api.
  docker-compose.yml
  frontend/__tests__/Home.test.tsx
  frontend/components/home/rsd/index.tsx
  frontend/package.json
Labels: bug
