Repository research-software-directory/RSD-as-a-service, pull requests merged in 2022-10, with the labels that each got.

#562 Improve ux serach boxes
  frontend/components/GlobalSearchAutocomplete/index.tsx
  frontend/components/form/Searchbox.tsx
  frontend/components/organisation/project/index.tsx
  frontend/components/organisation/software/index.tsx
  frontend/components/search/Searchbox.tsx
  frontend/components/user/organisations/index.tsx
  frontend/components/user/project/index.tsx
  frontend/components/user/software/index.tsx
  frontend/pages/organisations/index.tsx
  frontend/pages/projects/index.tsx
  frontend/pages/software/index.tsx
Labels: bug, UX fix

#566 UI cookies
  frontend/components/cookies/CookieConsentMatomo.tsx
  frontend/components/cookies/useCookieConsent.tsx
  frontend/components/icons/cookie.svg
  frontend/styles/global.css
Labels: bug, UX fix

#579 Search by doi using encoded url
  .gitignore
  frontend/components/projects/edit/impact/EditImpactProvider.tsx
  frontend/components/projects/edit/impact/impactForProjectApi.ts
  frontend/components/projects/edit/output/EditOutputProvider.tsx
  frontend/components/projects/edit/output/outputForProjectApi.ts
  frontend/components/software/edit/mentions/EditMentionsProvider.tsx
  frontend/components/software/edit/mentions/mentionForSoftwareApi.ts
  frontend/utils/editMentions.ts
  frontend/utils/getCrossref.ts
  frontend/utils/getDOI.ts
  frontend/utils/getDataCite.ts
  scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/CrossrefMention.java
  scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/DataciteMentionRepository.java
  scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/MainMentions.java
  scrapers/src/main/java/nl/esciencecenter/rsd/scraper/doi/PostgrestMentionRepository.java
Labels: bug

#477 419 no commits graph
  frontend/components/charts/d3LineChart/NoDataAvailableChart.tsx
  frontend/components/charts/d3LineChart/formatData.ts
  frontend/components/home/getHomepageCounts.ts
  frontend/components/software/CommitsChart.tsx
  frontend/components/software/GetStartedSection.tsx
  frontend/pages/software/[slug]/index.tsx
  frontend/types/SoftwareTypes.ts
  scrapers/src/main/java/nl/esciencecenter/rsd/scraper/ResponseException.java
  scrapers/src/main/java/nl/esciencecenter/rsd/scraper/Utils.java
  scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/AggregateContributionsPerWeekSIDecorator.java
  scrapers/src/main/java/nl/esciencecenter/rsd/scraper/git/GithubSI.java
  scrapers/src/test/java/nl/esciencecenter/rsd/scraper/git/AggregateContributionsPerWeekSIDecoratorTest.java
  scrapers/src/test/java/nl/esciencecenter/rsd/scraper/git/GithubSITest.java
Labels: feature
